# Generated by Django 6.0 on 2025-12-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_ppm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='tags',
        ),
    ]
