# Generated by Django 6.0 on 2025-12-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_ppm', '0002_remove_newsarticle_excerpt_remove_newsarticle_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
