# Generated by Django 6.0 on 2025-12-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_ppm', '0003_alter_newsarticle_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
