# Generated by Django 6.0 on 2025-12-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_ppm', '0004_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Opsional: link gambar dari internet', null=True),
        ),
    ]
