# Generated by Django 6.0 on 2025-12-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_ppm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dewan_guru', models.PositiveIntegerField(default=0)),
                ('total_santri', models.PositiveIntegerField(default=0)),
                ('mahasiswa', models.PositiveIntegerField(default=0)),
                ('mahasiswi', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistik Mahasiswa/i',
                'verbose_name_plural': 'Statistik Mahasiswa/i',
            },
        ),
    ]
