# Generated by Django 6.0 on 2025-12-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_ppm', '0002_sitestats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitestats',
            old_name='total_santri',
            new_name='total_mahasiswa',
        ),
    ]
