# Generated by Django 6.0 on 2025-12-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_ppm', '0003_rename_total_santri_sitestats_total_mahasiswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestats',
            name='total_mahasiswa',
        ),
    ]
