# Generated by Django 6.0 on 2025-12-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_ppm', '0004_remove_sitestats_total_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Judul Kegiatan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi Singkat')),
                ('image', models.ImageField(upload_to='gallery_photos/', verbose_name='Foto Kegiatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto Galeri',
                'verbose_name_plural': 'Galeri Kegiatan',
                'ordering': ['-created_at'],
            },
        ),
    ]
