# Generated by Django 6.0 on 2025-12-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_ppm', '0005_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(default='DOKUMENTASI', max_length=50, verbose_name='Kategori (misal: RUTIN, ORGANISASI)'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='gallery_photos/', verbose_name='Foto Dokumentasi'),
        ),
    ]
