# Generated by Django 6.0 on 2025-12-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_ppm', '0006_galleryphoto_category_alter_galleryphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(default='KEGIATAN', max_length=50, verbose_name='Label Kategori (misal: RUTIN, ORGANISASI)'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='gallery_photos/', verbose_name='Foto'),
        ),
    ]
