# Generated by Django 6.0 on 2025-12-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_ppm', '0007_alter_galleryphoto_category_alter_galleryphoto_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='website',
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(default='KEGIATAN', max_length=50, verbose_name='Label Kategori'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='gallery_photos/', verbose_name='Foto Dokumentasi'),
        ),
    ]
